.github/workflows/ci.yml
CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 4.3.2

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

4.3.3 버전 배포에 따른 README 포함 가이드 수정

chore:  release 4.3.3

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

4.3.4 버전 배포에 따른 README 포함 가이드 수정
Android 6 이하 기기에서 AdMuteView 의 비정상적인 렌더링 이슈 수정

chore: release 4.3.4

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 4.3.5

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/java-sample/src/main/res/values/strings.xml
example/kotlin-sample/build.gradle
example/kotlin-sample/src/main/res/values/strings.xml

4.3.6 버전 적용
AdMute 관련 크래시 대응
로컬 배포 이후 샘플 앱 테스트

chore: release 4.3.6

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/java-sample/src/main/java/com/naver/namexample/sample/SmartChannelFragment.java
example/kotlin-sample/build.gradle
example/kotlin-sample/src/main/java/com/naver/namexample/sample/SmartChannelFragment.kt

chore: release 4.4.0

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

4.4.1 버전 배포에 따른 README 포함 가이드 수정

chore: release 4.4.1

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle
example/settings.gradle

5.0.0 배포에 따른 샘플 및 가이드 내용 수정
apply new version & check the ads

chore: release 5.0.0

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

5.1.0 버전 배포에 따른 README 포함 가이드 수정

chore: release 5.1.0

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 5.1.2

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 5.1.3

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 5.2.0

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 5.3.0

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/java-sample/src/main/AndroidManifest.xml
example/java-sample/src/main/java/com/naver/namexample/sample/ImageBannerFragment.java
example/java-sample/src/main/java/com/naver/namexample/sample/NativeBannerFragment.java
example/java-sample/src/main/java/com/naver/namexample/sample/SmartChannelFragment.java
example/kotlin-sample/build.gradle
example/kotlin-sample/src/main/AndroidManifest.xml
example/kotlin-sample/src/main/java/com/naver/namexample/MainActivity.kt

6.0.0 버전 배포에 따른 README 포함 가이드 수정
Changelog 참조

chore: release 6.0.0

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

6.0.1 버전 배포에 대한 REAME 포함 가이드 수정

chore: release 6.0.1

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

NDA 배너에서 BannerViewLayoutType 을 `FLUID_WIDTH` 로 설정할 경우, 너비값 계산이 정상적으로 수행되지 않음.

chore: release 6.0.2

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle
example/settings.gradle

6.0.0~6.0.2 버전을 사용하는 여러 앱이 있을 경우, 하나의 앱만 설치 또는 업데이트가 가능하고 나머지 앱들은 설치 또는 업데이트가 불가능해지는 이슈 수정 
6.0.3 버전을 사용하는 복수개의 테스트 앱 설치시 설치가 정상적으로 동작하는 체크

chore: release 6.0.3

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
example/java-sample/build.gradle
example/java-sample/src/main/java/com/naver/namexample/MainMenuFragment.java
example/java-sample/src/main/java/com/naver/namexample/sample/InStreamFragment.java
example/java-sample/src/main/java/com/naver/namexample/video/SampleExoPlayerView.java
example/java-sample/src/main/res/layout/fragment_in_stream.xml
example/kotlin-sample/build.gradle
example/kotlin-sample/src/main/java/com/naver/namexample/MainMenuFragment.kt
example/kotlin-sample/src/main/java/com/naver/namexample/sample/InStreamFragment.kt
example/kotlin-sample/src/main/java/com/naver/namexample/sample/SmartChannelFragment.kt
example/kotlin-sample/src/main/java/com/naver/namexample/video/SampleExoPlayerView.kt
example/kotlin-sample/src/main/res/layout/fragment_in_stream.xml

6.0.4 버전 배포 및 In-Stream 모듈 배포 관련 샘플 및 문서 정리

chore: release 6.0.4

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/java-sample/src/main/java/com/naver/namexample/sample/InStreamFragment.java
example/java-sample/src/main/java/com/naver/namexample/video/SampleExoPlayerView.java
example/java-sample/src/main/res/layout/fragment_in_stream.xml
example/kotlin-sample/build.gradle
example/kotlin-sample/src/main/java/com/naver/namexample/sample/InStreamFragment.kt
example/kotlin-sample/src/main/res/layout/fragment_in_stream.xml

chore: release 6.0.5

---

CHANGELOG.md
README.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 6.1.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

update to NAM 6.1.1
run the sample app on local device

chore: release 6.1.1

---

.github/pull_request_template.md
CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

* support global privacy policy on C2S
* **vungle:** fix a mis matching error code on Vungle rendering error

chore: release 6.3.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 6.4.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 6.4.1

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

Update NAM SDK version to 6.4.2

chore: release 6.4.2

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 6.5.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/java-sample/src/main/java/com/naver/namexample/sample/ImageBannerFragment.java
example/kotlin-sample/build.gradle
example/kotlin-sample/src/main/java/com/naver/namexample/MainActivity.kt
example/kotlin-sample/src/main/java/com/naver/namexample/sample/ImageBannerFragment.kt
example/kotlin-sample/src/main/java/com/naver/namexample/sample/NativeBannerFragment.kt
example/kotlin-sample/src/main/java/com/naver/namexample/sample/SmartChannelFragment.kt

chore: release 6.6.1

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle
example/kotlin-sample/src/main/java/com/naver/namexample/sample/NativeBannerFragment.kt

* **core:** fix a bug when binding native ads in RecyclerView

chore: release 6.6.3

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 6.7.1

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 6.7.2

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 7.0.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 7.0.1

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 7.1.1

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

* add a language setting on in-stream ad
* `ViewObserver` does not work with ad that is displayed on top of other apps

chore: release 7.2.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

* **applovin:** add error handling at initialization
* **fan:** add error handling when load native ad
* **ironsource:** remove IronSource banner
* **unity:** fix crash when passing application context when requesting Unity banner
* **vungle:** add error handling at initialization

chore: release 7.2.1

---

CHANGELOG.md
README.md

* **This version has an issue. Use the older NAM SDK v7.3.0 instead.**
* support clickable control view type for native outstream ad 
* add background color and text colors to native ad

chore: deprecated 7.4.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 7.4.1

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

chore: release 7.4.2

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

- add corner option for where the ad choices icon is
- **ndarichmedia:** add English resources to Richmedia AD

chore: release 7.4.3

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
example/java-sample/build.gradle
example/kotlin-sample/build.gradle

mavenCentral 싱크 후 데모 앱 확인하고 머지하겠습니다~

chore: release 7.4.4

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
java-sample/build.gradle
kotlin-sample/build.gradle

* support carousel media in native ads
* **nda:** align `discount` and `price` TextViews in Shopping NDA ad
* **nda:** remove unused resources

chore: release 7.5.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
java-sample/build.gradle
kotlin-sample/build.gradle

chore: release 7.5.1

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
java-sample/build.gradle
kotlin-sample/build.gradle

* fix minor issues in `Shopping NDA` ad
* bump minSdk from 19 to 21
* **core:** send ad loaded event after listener setting in Rewarded/Interstitial AD
* update DSP sdk

chore: release 7.5.2

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
java-sample/build.gradle
kotlin-sample/build.gradle

- **applovin:** bump `applovin` to 12.5.0
- **nda:** refactor `SlotsView`'s padding handling
- **unity:** update `Unity` to 4.10.0

chore: release 7.5.3

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
java-sample/build.gradle
kotlin-sample/build.gradle

* **lan:** add lan extension
* support shopping label ad

chore: release 7.6.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
java-sample/build.gradle
kotlin-sample/build.gradle

chore: release 7.6.1

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
java-sample/build.gradle
java-sample/src/main/java/com/naver/namexample/sample/InStreamFragment.java
kotlin-sample/build.gradle
kotlin-sample/src/main/java/com/naver/namexample/sample/InStreamFragment.kt

chore: release 7.6.2

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
java-sample/build.gradle
kotlin-sample/build.gradle

* support shopping search native ad
* **nda:** fix video not pausing when clicking on ad choices
* **video:** show saved last frame on FullScreenAD
* add GFP/NDA 1+3 View
* **ironsource:** refactor IronSource Integration to load multiple instance id
* **nda:** modify badge UI on shopping nda ad
* **nda:** show the CTA button on last frame for the Rewarded AD
* reuse innerAdView inside `GfpNativeAdView` without inflating it

chore: release 7.7.0

---

.github/workflows/ci.yml
CHANGELOG.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
java-sample/build.gradle
kotlin-sample/build.gradle

chore: release 7.7.1

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle

chore: release 7.7.2

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle

* **nda:** support the Smart Channel Flicking AD
* **nda:** fix image badge size error in shopping label ad
* **nda:** add content description to SlotsView

chore: release 7.8.0

---

CHANGELOG.md
README.md
java-sample/build.gradle
kotlin-sample/build.gradle

* fix height value calculation error in `NativeTemplateView`

chore: release 7.8.1

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle

* fix animation rendering issues on devices below Android 9
* fix VAST parsing error
* allow redirects for all http requests by default

chore: release 7.9.0

---

CHANGELOG.md
README.md
docs/ad-formats/in_stream.md
docs/ad-providers/dfp.md
docs/ad-providers/fan.md
docs/ad-providers/inmobi.md
docs/ad-providers/ironsource.md
docs/ad-providers/nda.md
java-sample/build.gradle
java-sample/src/main/java/com/naver/namexample/MainActivity.java
java-sample/src/main/java/com/naver/namexample/sample/InStreamFragment.java
java-sample/src/main/java/com/naver/namexample/video/SampleExoPlayerView.java
kotlin-sample/build.gradle
kotlin-sample/src/main/java/com/naver/namexample/MainActivity.kt
kotlin-sample/src/main/java/com/naver/namexample/sample/InStreamFragment.kt
kotlin-sample/src/main/java/com/naver/namexample/video/SampleExoPlayerView.kt

chore: release 8.0.0

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle

* **adplayer:** fixing how skip offsets are calculated in in-stream ad
* modify user interest visible ratio
| Artifact name                             | Version mapped this BoM |
|-------------------------------------------|-------------------------|
| com.naver.gfpsdk:nam-core                 | 8.2.1                   |
| com.naver.gfpsdk:nam-adplayer             | 8.2.1                   |
| com.naver.gfpsdk.mediation:nam-nda        | 8.2.1                   |
| com.naver.gfpsdk.mediation:nam-ndavideo   | 8.2.1                   |
| com.naver.gfpsdk.mediation:nam-applovin   | 12.6.1.0                |
| com.naver.gfpsdk.mediation:nam-aps        | 9.10.2.0                |
| com.naver.gfpsdk.mediation:nam-dfp        | 23.3.0.0                |
| com.naver.gfpsdk.mediation:nam-dt …

chore: release 8.2.1

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle
mediation/applovin/README.md
mediation/aps/README.md
mediation/dfp/README.md
mediation/dt/README.md
mediation/fan/README.md
mediation/inmobi/README.md
mediation/ironsource/README.md
mediation/lan/README.md
mediation/unity/README.md
mediation/vungle/README.md

chore: release 8.2.4

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle
mediation/dfp/README.md
mediation/fan/README.md
mediation/inmobi/README.md
mediation/lan/README.md

chore: release 8.2.5

---

.github/workflows/android.yml

- CI 타겟 브랜치 수정
PR 에서 CI 가 안 돌고 있어서 확인해보니 브랜치명이 "master" 가 아니라 "main" 이어서 수정했습니다.

ci: fix ci target branch

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle.kts
mediation/dt/README.md

chore: release 8.3.1

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle.kts
mediation/applovin/README.md
mediation/bidmachine/README.md
mediation/dt/README.md
mediation/lan/README.md

chore: release 8.4.0

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle.kts
mediation/applovin/README.md

* **nda:** size of special da shopping nda ad was miscalculated
|Artifact name|Version mapped this BoM|
|---|---|
|com.naver.gfpsdk:nam-core|8.4.1|
|com.naver.gfpsdk:nam-adplayer|8.4.1|
|com.naver.gfpsdk.mediation:nam-nda|8.4.1|
|com.naver.gfpsdk.mediation:nam-ndavideo|8.4.1|
|com.naver.gfpsdk.mediation:nam-applovin|13.2.0.0|
|com.naver.gfpsdk.mediation:nam-aps|9.10.2.1|
|com.naver.gfpsdk.mediation:nam-dfp|23.3.0.2|
|com.naver.gfpsdk.mediation:nam-dt|8.3.6.1|
|com.naver.gfpsdk.mediation:nam-fan|6.18.0.3|
|com.naver.gfpsdk.mediation:nam-inmobi|10.8.0.0|
|com.naver.gfpsdk.mediation:nam-ironsource|8.4.0.2|
|com.naver.gfpsdk.mediation:nam-lan|2.9.20241129.2|
|com.naver.gfpsdk.mediation:nam-unity|4.12.3.1|
|com.naver.gfpsdk.mediation:nam-vungle|7.4.1.1| …

chore: release 8.4.1

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle.kts

* **nda:** add `asynclayoutinflater` dependency to prevent runtime error ([7e4598e](https://oss.navercorp.com/da-ssp-app-sdk/naver_sdk_aos/commit/7e4598ea8b421f040c55de126efd7895624c19d8))
|Artifact name|Version mapped this BoM|
|---|---|
|com.naver.gfpsdk:nam-core|8.4.2|
|com.naver.gfpsdk:nam-adplayer|8.4.2|
|com.naver.gfpsdk.mediation:nam-nda|8.4.2|
|com.naver.gfpsdk.mediation:nam-ndavideo|8.4.2|
|com.naver.gfpsdk.mediation:nam-applovin|13.2.0.0|
|com.naver.gfpsdk.mediation:nam-aps|9.10.2.1|
|com.naver.gfpsdk.mediation:nam-bidmachine|3.1.1.1|
|com.naver.gfpsdk.mediation:nam-chartboost|9.7.0.0|
|com.naver.gfpsdk.mediation:nam-dfp|23.3.0.2|
|com.naver.gfpsdk.mediation:nam-dt|8.3.6.1|
|com.naver.gfpsdk.mediation:nam-fan|6.18.0.3|
|com.naver.gfpsdk.mediation:nam-inmobi|10.8.0.0| …

chore: release 8.4.2

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle.kts
mediation/applovin/README.md
mediation/aps/README.md
mediation/bidmachine/README.md
mediation/chartboost/README.md
mediation/dfp/README.md
mediation/dt/README.md
mediation/fan/README.md
mediation/inmobi/README.md
mediation/ironsource/README.md
mediation/lan/README.md
mediation/unity/README.md
mediation/vungle/README.md

chore: release 8.4.3

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle.kts
mediation/bidmachine/README.md
mediation/ironsource/README.md
mediation/lan/README.md
settings.gradle.kts

* improve event handling to ensure consistent behavior
|Artifact name|Version mapped this BoM|
|---|---|
|com.naver.gfpsdk:nam-core|8.4.5|
|com.naver.gfpsdk:nam-adplayer|8.4.5|
|com.naver.gfpsdk.mediation:nam-nda|8.4.5|
|com.naver.gfpsdk.mediation:nam-ndavideo|8.4.5|
|com.naver.gfpsdk.mediation:nam-applovin|13.2.0.1|
|com.naver.gfpsdk.mediation:nam-aps|9.10.2.2|
|com.naver.gfpsdk.mediation:nam-bidmachine|3.1.1.3|
|com.naver.gfpsdk.mediation:nam-chartboost|9.7.0.1|
|com.naver.gfpsdk.mediation:nam-dfp|23.3.0.3|
|com.naver.gfpsdk.mediation:nam-dt|8.3.6.2|
|com.naver.gfpsdk.mediation:nam-fan|6.18.0.4|
|com.naver.gfpsdk.mediation:nam-inmobi|10.8.0.1|
|com.naver.gfpsdk.mediation:nam-ironsource|8.4.0.4|
|com.naver.gfpsdk.mediation:nam-lan|2.9.20250110.0| …

chore: release 8.4.5

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle.kts

* **nda:** fix click handling issue for specific native ad 
|Artifact name|Version mapped this BoM|
|---|---|
|com.naver.gfpsdk:nam-core|8.5.1|
|com.naver.gfpsdk:nam-adplayer|8.5.1|
|com.naver.gfpsdk.mediation:nam-nda|8.5.1|
|com.naver.gfpsdk.mediation:nam-ndavideo|8.5.1|
|com.naver.gfpsdk.mediation:nam-applovin|13.2.0.1|
|com.naver.gfpsdk.mediation:nam-aps|9.10.2.2|
|com.naver.gfpsdk.mediation:nam-bidmachine|3.1.1.3|
|com.naver.gfpsdk.mediation:nam-chartboost|9.7.0.1|
|com.naver.gfpsdk.mediation:nam-dfp|23.3.0.4|
|com.naver.gfpsdk.mediation:nam-dt|8.3.6.2|
|com.naver.gfpsdk.mediation:nam-fan|6.18.0.4|
|com.naver.gfpsdk.mediation:nam-inmobi|10.8.0.1|
|com.naver.gfpsdk.mediation:nam-ironsource|8.4.0.4|
|com.naver.gfpsdk.mediation:nam-lan|2.9.20250110.0| …

chore: release 8.5.1

---

CHANGELOG.md
java-sample/build.gradle
java-sample/src/main/java/com/naver/namexample/sample/ImageBannerFragment.java
java-sample/src/main/java/com/naver/namexample/sample/InStreamFragment.java
java-sample/src/main/java/com/naver/namexample/sample/NativeBannerFragment.java
java-sample/src/main/java/com/naver/namexample/sample/RewardedFragment.java
java-sample/src/main/java/com/naver/namexample/sample/SmartChannelFragment.java
kotlin-sample/build.gradle.kts
kotlin-sample/src/main/java/com/naver/namexample/sample/ImageBannerFragment.kt
kotlin-sample/src/main/java/com/naver/namexample/sample/NativeBannerFragment.kt
kotlin-sample/src/main/java/com/naver/namexample/sample/SmartChannelFragment.kt

chore: release 8.6.0

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle.kts

chore: release 8.6.1

---

CHANGELOG.md
java-sample/build.gradle
kotlin-sample/build.gradle.kts

chore: release 8.8.1

---

CHANGELOG.md
README.md
build.gradle.kts
docs/ad-formats/interstitial.md
java-sample/build.gradle
java-sample/src/main/java/com/naver/namexample/MainMenuFragment.java
java-sample/src/main/java/com/naver/namexample/sample/InterstitialFragment.java
java-sample/src/main/res/layout/fragment_interstitial.xml
kotlin-sample/build.gradle.kts
kotlin-sample/src/main/java/com/naver/namexample/MainMenuFragment.kt
kotlin-sample/src/main/java/com/naver/namexample/sample/InterstitialFragment.kt
kotlin-sample/src/main/res/layout/fragment_interstitial.xml
mediation/applovin/README.md
mediation/aps/README.md
mediation/bidmachine/README.md
mediation/chartboost/README.md
mediation/dfp/README.md
mediation/dt/README.md
mediation/fan/README.md
mediation/inmobi/README.md
mediation/ironsource/README.md
mediation/lan/README.md
mediation/nda/README.md
mediation/pangle/README.md
mediation/unity/README.md
mediation/vungle/README.md
settings.gradle.kts

chore: release 8.9.0
